config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  resources :favorite_recipes, only: [:index]
  resources :recipes do
    resources :favorite_recipes, only: [:create]
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient

  validates :unit, :amount, presence: true
  validates :unit, inclusion: { in: ['grams', 'liters', 'cups'] }
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_one :dose, dependent: :destroy
  has_many :recipes, through: :doses

  validates :name, presence: true

  accepts_nested_attributes_for :dose
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  has_many :favorite_recipes, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  has_one_attached :photo
  has_rich_text :description

  validates :name, uniqueness: true
  validates :name, :photo, presence: true

  accepts_nested_attributes_for :categories

  pg_search_scope :search_by_name,
    against: [ :name ],
    associated_against: {
      categories: [:name],
      ingredients: [:name]
    },
    using: {
      tsearch: { prefix: true, any_word: true }
    }

  scope :sort_by_most_recent, lambda { order(created_at: :desc) }
  scope :sort_by_alphabet, lambda { order(:name) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_recipe

  def new
    @dose = Dose.new
    @dose.build_ingredient
    authorize @dose
  end

  def create
    @dose = Dose.new(dose_params)
    authorize @dose
    @dose.create_ingredient(name: params[:dose][:ingredient_attributes][:name])
    @dose.recipe = @recipe
    if @dose.save
      redirect_to new_recipe_dose_path(@recipe)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.last
    authorize @dose
    @dose.destroy
    redirect_to new_recipe_dose_path(@recipe)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def dose_params
    params.require(:dose).permit(:unit, :amount, ingredient_attributes: [:id, :name])
  end
end

app/controllers/favorite_recipes_controller.rb
class FavoriteRecipesController < ApplicationController
  def index
    @favorite_recipes = policy_scope(FavoriteRecipe).where(user: current_user)
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    favorite_exists = FavoriteRecipe.where(recipe: @recipe, user: 1)
    authorize favorite_exists
    if favorite_exists.count.positive?
      favorite_exists.destroy_all
    else
      @favorite_recipe = FavoriteRecipe.new(recipe: @recipe, user: current_user)
      authorize @favorite_recipe
      if @favorite_recipe.save
        redirect_to back_with_anchor anchor: @recipe.id
      else
        render 'recipes/show'
      end
    end
  end

  private

  def back_with_anchor(anchor: '')
    "#{request.referrer}##{anchor}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:edit, :update, :destroy]
  def index
    @admin = !current_user.nil? && current_user.admin == true
    @recipes = policy_scope(Recipe).includes(:favorite_recipes, photo_attachment: :blob).where(nil)
    @recipes = Recipe.search_by_name(params[:search]) if params[:search].present?
    @recipes = Recipe.sort_by_most_recent if params[:recent].present?
    @recipes = Recipe.sort_by_alphabet if params[:alphabetical].present?

    @favorite_recipe = FavoriteRecipe.new
  end

  def show
    @admin = !current_user.nil? && current_user.admin == true
    @recipe = Recipe.includes(:doses, :ingredients).find(params[:id])
    authorize @recipe
    @favorite_recipe = FavoriteRecipe.new
    @favorite_exists = FavoriteRecipe.where(recipe: @recipe, user: current_user).count.positive?
  end

  def new
    @recipe = Recipe.new
    2.times { @recipe.categories.build }
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    authorize @recipe
    if @recipe.save
      redirect_to new_recipe_dose_path(@recipe)
    else
      render :new
    end
  end

  def edit
    authorize @recipe
  end

  def update
    authorize @recipe
    if @recipe.update(recipe_params)
      redirect_to new_recipe_dose_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    authorize @recipe
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :photo, categories_attributes: [:id, :name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/doses/new.html.erb
<div class="page-container">
  <div class="desktop-button-flex">
    <h3>Zutaten hinzufügen</h3>
    <% if @recipe.doses.count > 0 %>
      <%= link_to 'Fertig', recipe_path(@recipe), class: 'btn btn-petrol my-3' %>
    <% end %>
  </div>

  <div class="ingredients mb-5">
    <% unless @recipe.ingredients.blank? %>
      <h5>Bereits hinzugefügt</h5>
      <ul><% @recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.dose.amount %> <%= ingredient.dose.unit %>
        <%= ingredient.name %></li>  
      <% end %></ul>
    <% end %>
    <%#= link_to 'Löschen', recipe_dose_path(@recipe), method: :delete %>
  </div>

  <%= form_with model: @dose, url: recipe_doses_url do |form| %>
    <div class="form-group">
      <%= form.text_field :amount, placeholder: 'Menge' , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.text_field :unit, placeholder: 'Einheit' , class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.fields_for :ingredient do |cat_form| %>
        <%= cat_form.text_field :name, placeholder: 'Name der Zutat', class: "form-control mb-1", required: true  %>
      <% end %>
    </div>

    <%= form.submit 'Zutat hinzufügen', class: "btn-red mt-3 mb-5" %>
  <% end %>
</div>

app/views/favorite_recipes/index.html.erb
<div class="page-container">
    <h2 class="mb-5">Lieblings-Rezepte</h2>

  <div class="cards">
    <% @favorite_recipes.each do |fav| %>
      <div class="recipe-card">
        <% if fav.recipe.photo.attached? %>
          <%= cl_image_tag fav.recipe.photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
        
        <div class="recipe-infos">
          <div class="flex flex-jc-sb mb-2">
            <h2 style="max-width: 82%;"><%= link_to fav.recipe.name, recipe_path(fav.recipe) %></h2>
            <%= form_with model: @favorite_recipe, url: recipe_favorite_recipes_url(fav.recipe) do |form| %>
              <%= button_tag type: 'submit', class: 'btn-text-white', id: 'btn-heart', style:'padding:0;' do %>
                <% if FavoriteRecipe.where(recipe: fav.recipe, user: current_user).count.positive? %>
                  <i class="fas fa-heart" id='icon-heart'></i>
                <% else %>
                  <i class="far fa-heart" id='icon-heart'></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/recipes/_edit_recipe_form.html.erb
  <%= form_with model: @recipe do |form| %>
  <div class="form-group">
    <%= form.text_field :name, placeholder: 'Name für dein Rezept' , class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.fields_for :categories do |cat_form| %>
      <%= cat_form.text_field :name, placeholder: 'Rezeptkategorie', class: "form-control", required: true  %>
    <% end %>
  </div>

  <div class="form-group mt-5">
    <%= form.rich_text_area :description, placeholder: 'Beschreibe die Zubereitung Schritt für Schritt' , class: "form-control" %>
  </div>

  <div class="form-group mt-5 mb-5">
    <i class="fas fa-camera-retro"></i>  <%= form.label :photo, 'Lade ein Foto hoch' %>  <i class="fas fa-camera-retro"></i>
    <%= form.file_field :photo, style: 'width: 60vw;' %>
  </div>
  <%= form.submit 'Zutaten bearbeiten', class: "btn-petrol" %>
<% end %>

app/views/recipes/_favorite_recipe_form_index.html.erb
<%= form_with model: @favorite_recipe, url: recipe_favorite_recipes_url(recipe) do |form| %>
  <%= button_tag type: 'submit', class: 'btn-text-white', id: 'btn-heart', style:'padding:0;' do %>
    <% if FavoriteRecipe.where(recipe: recipe, user: current_user).count.positive? %>
      <i class="fas fa-heart" id='icon-heart'></i>
    <% else %>
      <i class="far fa-heart" id='icon-heart'></i>
    <% end %>
  <% end %>
<% end %>

app/views/recipes/_favorite_recipe_form_show.html.erb
<%= form_with model: @favorite_recipe, url: recipe_favorite_recipes_url(@recipe) do |form| %>
  <%= button_tag type: 'submit', class: 'btn-text', id: 'btn-heart' do %>
    <% if @favorite_exists %>
      <i class="fas fa-heart" id='icon-heart'></i>
    <% else %>
      <i class="far fa-heart" id='icon-heart'></i>
    <% end %>
  <% end %>
<% end %>

app/views/recipes/_new_recipe_form.html.erb
<%= form_with model: @recipe do |form| %>
  <div class="form-group">
    <%= form.text_field :name, placeholder: 'Name für dein Rezept' , class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.fields_for :categories do |cat_form| %>
      <%= cat_form.text_field :name, placeholder: 'Rezeptkategorie', class: "form-control mb-1", required: true  %>
    <% end %>
  </div>

  <div class="form-group mt-4">
    <%= form.rich_text_area :description, placeholder: 'Beschreibe die Zubereitung Schritt für Schritt' , class: "form-control" %>
  </div>
  <div class="form-group mt-5 mb-5">
    <i class="fas fa-camera-retro"></i>  <%= form.label :photo, 'Lade ein Foto hoch' %>  <i class="fas fa-camera-retro"></i>
    <%= form.file_field :photo, required: true, style: 'width: 60vw;' %>
  </div>
  <%= form.submit 'Zutaten hinzufügen', class: "btn-red" %>
<% end %>

app/views/recipes/_search_and_filters.html.erb
<div class="search-form-control">
  <%= form_tag recipes_path, method: :get do |form| %>
    <%= text_field_tag :search, params[:search], class: "form-control mb-3", placeholder: "Finde ein Rezept mit Name, Küche oder Zutaten" %>
    <%= submit_tag "Suchen", class: "btn btn-red" %>
  <% end %>
</div>

<%= form_with model: @recipe, method: :get, class: 'mb-4' do |form| %> 
  <%= form.label :recent, 'Neue zuerst' %>
  <%= check_box_tag :recent, true, (params[:alphabetical] == 'true'), onclick: 'this.form.submit()' %>
  <%= form.label :alphabetical, 'A-Z' %>
  <%= check_box_tag :alphabetical, true, (params[:alphabetical] == 'true'), onclick: 'this.form.submit()' %>
<% end %>

app/views/recipes/edit.html.erb
<div class="page-container">
  <h3 class="mb-4">Rezept bearbeiten</h3>

  <%= render 'edit_recipe_form' %>
</div>

app/views/recipes/index.html.erb
<div class="page-container">
  <div class="mobile-container">
    <h1 class="mb-4">Alle Rezepte</h1>

    <%= render "search_and_filters" %>
  </div>

  <div class="cards">
    <% @recipes.each do |recipe| %>
      <div class="recipe-card" id="<%= recipe.id %>">
        <% if recipe.photo.attached? %>
          <%= cl_image_tag recipe.photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
        
        <div class="recipe-infos">
          <div class="flex flex-jc-sb mb-2">
            <h2 style="max-width: 82%;"><%= link_to recipe.name, recipe_path(recipe) %></h2>

            <%= render partial: "favorite_recipe_form_index", locals: {recipe: recipe} %>
          </div>
          <%= link_to "Löschen", recipe, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'delete' if @admin %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="page-container">
  <h2 class="mb-5">Neues Rezept</h2>
  
  <%= render "new_recipe_form" %>
</div>

app/views/recipes/show.html.erb
<div class="page-container">
  <div class="mobile-container">
    <div class="desktop-button-flex">
      <div class="flex">
        <h1><%= @recipe.name %></h1>
        <%= render "favorite_recipe_form_show" %>
      </div>
      <%= link_to 'Rezept bearbeiten', edit_recipe_path(@recipe), class: 'btn-text my-3' if @admin %>
    </div>

    <ul class="mb-4">
    <% @recipe.categories.each do |category| %>
      <li><%= category.name %></li>
    <% end %> 
    </ul>

    <div class="desktop-flex my-3">
      <div class="main-image">
        <% if @recipe.photo.attached? %>
          <%= cl_image_tag @recipe.photo.key, height: 300, width: 300, crop: :fill %>
        <% end %>
      </div>

      <div class="ingredients">
        <h4>Zutaten</h4>
        <ul>
          <% @recipe.doses.each do |dose| %>
            <li><%= dose.amount %> <%= dose.unit %>
            <%= dose.ingredient.name %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="steps mt-4">
      <h4>Zubereitung</h4>
      <div class="cooking-steps mx-2">
        <%= @recipe.description %>
      </div>
    </div>

    <%= link_to 'Alle Rezepte', recipes_path, class: 'btn-petrol my-5' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="flex flex-jc-sb flex-ai-c px-4">
    <%= link_to root_path, class: "header_logo" do %>
      <%= image_tag('yum.jpg', alt: 'Yum logo')%>
    <% end %>

    <div class="openMenu"><i class="fa fa-bars"></i></div>
    <ul class="mainMenu header_links flex flex-jc-sa flex-ai-c">
      <li><%= link_to "Alle Rezepte", recipes_path %></li>
      <li><%= link_to "Rezept hinzufügen", new_recipe_path if !current_user.nil? && current_user.admin == true %></li>
      <li><%= link_to "Meine Favoriten", favorite_recipes_path %></li>
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "my-3" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "my-3" %>
      <% end %>

      <div class="closeMenu"><i class="fa fa-times"></i></div>
    </ul>
  </nav>
</header>